let a = window.localStorage.getItem("login")
document.getElementById("nik").innerHTML=a

function off(){
    document.querySelector(".not").style.display='none';
    document.querySelector(".not2").style.display='inline';
    
}
function off2(){
    document.querySelector(".not2").style.display='none';
    document.querySelector(".not").style.display='inline';
    
}
function ind(){
    document.querySelector('.album').classList.toggle("new2");
    document.querySelector(".kpop1").classList.toggle("new");
    document.querySelector(".kpop2").classList.toggle("new");
    document.querySelector(".kpop3").classList.toggle("new");
    document.querySelector(".kpop9").classList.toggle("new");
    document.querySelector(".kpop4").classList.toggle("new");
    document.querySelector(".kpop5").classList.toggle("new");
    document.querySelector(".kpop6").classList.toggle("new");
    document.querySelector(".kpop7").classList.toggle("new");
    document.querySelector(".kpop8").classList.toggle("new");
    document.querySelector(".hiphop1").classList.toggle("new");
    document.querySelector(".hiphop2").classList.toggle("new")
    document.querySelector(".hiphop3").classList.toggle("new")
    document.querySelector(".hiphop4").classList.toggle("new")
    document.querySelector(".hiphop5").classList.toggle("new")
    document.querySelector(".hiphop6").classList.toggle("new")
    document.querySelector(".hiphop7").classList.toggle("new")
    document.querySelector(".hiphop8").classList.toggle("new")
    document.querySelector(".hiphop9").classList.toggle("new")
    document.querySelector(".hiphop10").classList.toggle("new")
    document.querySelector(".hiphop11").classList.toggle("new")
    document.querySelector(".hiphop12").classList.toggle("new")
    document.querySelector(".hiphop13").classList.toggle("new")
    document.querySelector(".hiphop14").classList.toggle("new")
    document.querySelector(".hiphop15").classList.toggle("new")
    document.querySelector(".hiphop16").classList.toggle("new")
    document.querySelector(".hiphop17").classList.toggle("new")
    document.querySelector(".hiphop18").classList.toggle("new")
    document.querySelector(".hiphop19").classList.toggle("new")
    document.querySelector(".hiphop20").classList.toggle("new")
    document.querySelector(".rb1").classList.toggle("new")
    document.querySelector(".rb2").classList.toggle("new")
    document.querySelector(".rb3").classList.toggle("new")
    document.querySelector(".rb4").classList.toggle("new")
    document.querySelector(".rb5").classList.toggle("new")
    document.querySelector(".rb6").classList.toggle("new")
    document.querySelector(".rb7").classList.toggle("new")
    document.querySelector(".rb8").classList.toggle("new")
    document.querySelector(".rb9").classList.toggle("new")
    document.querySelector(".rb10").classList.toggle("new")
    document.querySelector(".rb11").classList.toggle("new")
    document.querySelector(".rock1").classList.toggle("new")
    document.querySelector(".rock2").classList.toggle("new")
    document.querySelector(".rock3").classList.toggle("new")
    document.querySelector(".rock4").classList.toggle("new")
    document.querySelector(".rock5").classList.toggle("new")
    document.querySelector(".rock6").classList.toggle("new")
    document.querySelector(".rock7").classList.toggle("new")
    document.querySelector(".rock8").classList.toggle("new")
    document.querySelector(".rock9").classList.toggle("new")
    document.querySelector(".rock10").classList.toggle("new")
    document.querySelector(".rock11").classList.toggle("new")
    document.querySelector(".rock12").classList.toggle("new")
    document.querySelector(".rock13").classList.toggle("new")
    document.querySelector(".rock14").classList.toggle("new")
    document.querySelector(".rock15").classList.toggle("new")
}
function rb(){
    document.querySelector('.album').classList.toggle("new2");
    document.querySelector(".kpop1").classList.toggle("new");
    document.querySelector(".kpop2").classList.toggle("new");
    document.querySelector(".kpop3").classList.toggle("new");
    document.querySelector(".kpop9").classList.toggle("new");
    document.querySelector(".kpop4").classList.toggle("new");
    document.querySelector(".kpop5").classList.toggle("new");
    document.querySelector(".kpop6").classList.toggle("new");
    document.querySelector(".kpop7").classList.toggle("new");
    document.querySelector(".kpop8").classList.toggle("new");
    document.querySelector(".hiphop1").classList.toggle("new");
    document.querySelector(".hiphop2").classList.toggle("new")
    document.querySelector(".hiphop3").classList.toggle("new")
    document.querySelector(".hiphop4").classList.toggle("new")
    document.querySelector(".hiphop5").classList.toggle("new")
    document.querySelector(".hiphop6").classList.toggle("new")
    document.querySelector(".hiphop7").classList.toggle("new")
    document.querySelector(".hiphop8").classList.toggle("new")
    document.querySelector(".hiphop9").classList.toggle("new")
    document.querySelector(".hiphop10").classList.toggle("new")
    document.querySelector(".hiphop11").classList.toggle("new")
    document.querySelector(".hiphop12").classList.toggle("new")
    document.querySelector(".hiphop13").classList.toggle("new")
    document.querySelector(".hiphop14").classList.toggle("new")
    document.querySelector(".hiphop15").classList.toggle("new")
    document.querySelector(".hiphop16").classList.toggle("new")
    document.querySelector(".hiphop17").classList.toggle("new")
    document.querySelector(".hiphop18").classList.toggle("new")
    document.querySelector(".hiphop19").classList.toggle("new")
    document.querySelector(".hiphop20").classList.toggle("new")
    document.querySelector(".rock1").classList.toggle("new")
    document.querySelector(".rock2").classList.toggle("new")
    document.querySelector(".rock3").classList.toggle("new")
    document.querySelector(".rock4").classList.toggle("new")
    document.querySelector(".rock5").classList.toggle("new")
    document.querySelector(".rock6").classList.toggle("new")
    document.querySelector(".rock7").classList.toggle("new")
    document.querySelector(".rock8").classList.toggle("new")
    document.querySelector(".rock9").classList.toggle("new")
    document.querySelector(".rock10").classList.toggle("new")
    document.querySelector(".rock11").classList.toggle("new")
    document.querySelector(".rock12").classList.toggle("new")
    document.querySelector(".rock13").classList.toggle("new")
    document.querySelector(".rock14").classList.toggle("new")
    document.querySelector(".rock15").classList.toggle("new")
    document.querySelector(".indie1").classList.toggle("new")
    document.querySelector(".indie2").classList.toggle("new")
    document.querySelector(".indie3").classList.toggle("new")
    document.querySelector(".indie4").classList.toggle("new")
    document.querySelector(".indie5").classList.toggle("new")
    document.querySelector(".indie6").classList.toggle("new")
    document.querySelector(".indie7").classList.toggle("new")
    document.querySelector(".indie8").classList.toggle("new")
    document.querySelector(".indie9").classList.toggle("new")
    document.querySelector(".indie10").classList.toggle("new")
    document.querySelector(".indie11").classList.toggle("new")
    document.querySelector(".indie12").classList.toggle("new")
}
function rock(){
    document.querySelector('.album').classList.toggle("new2");
    document.querySelector(".kpop1").classList.toggle("new");
    document.querySelector(".kpop2").classList.toggle("new");
    document.querySelector(".kpop3").classList.toggle("new");
    document.querySelector(".kpop9").classList.toggle("new");
    document.querySelector(".kpop4").classList.toggle("new");
    document.querySelector(".kpop5").classList.toggle("new");
    document.querySelector(".kpop6").classList.toggle("new");
    document.querySelector(".kpop7").classList.toggle("new");
    document.querySelector(".kpop8").classList.toggle("new");
    document.querySelector(".hiphop1").classList.toggle("new");
    document.querySelector(".hiphop2").classList.toggle("new")
    document.querySelector(".hiphop3").classList.toggle("new")
    document.querySelector(".hiphop4").classList.toggle("new")
    document.querySelector(".hiphop5").classList.toggle("new")
    document.querySelector(".hiphop6").classList.toggle("new")
    document.querySelector(".hiphop7").classList.toggle("new")
    document.querySelector(".hiphop8").classList.toggle("new")
    document.querySelector(".hiphop9").classList.toggle("new")
    document.querySelector(".hiphop10").classList.toggle("new")
    document.querySelector(".hiphop11").classList.toggle("new")
    document.querySelector(".hiphop12").classList.toggle("new")
    document.querySelector(".hiphop13").classList.toggle("new")
    document.querySelector(".hiphop14").classList.toggle("new")
    document.querySelector(".hiphop15").classList.toggle("new")
    document.querySelector(".hiphop16").classList.toggle("new")
    document.querySelector(".hiphop17").classList.toggle("new")
    document.querySelector(".hiphop18").classList.toggle("new")
    document.querySelector(".hiphop19").classList.toggle("new")
    document.querySelector(".hiphop20").classList.toggle("new")
    document.querySelector(".rb1").classList.toggle("new")
    document.querySelector(".rb2").classList.toggle("new")
    document.querySelector(".rb3").classList.toggle("new")
    document.querySelector(".rb4").classList.toggle("new")
    document.querySelector(".rb5").classList.toggle("new")
    document.querySelector(".rb6").classList.toggle("new")
    document.querySelector(".rb7").classList.toggle("new")
    document.querySelector(".rb8").classList.toggle("new")
    document.querySelector(".rb9").classList.toggle("new")
    document.querySelector(".rb10").classList.toggle("new")
    document.querySelector(".rb11").classList.toggle("new")
    document.querySelector(".indie1").classList.toggle("new")
    document.querySelector(".indie2").classList.toggle("new")
    document.querySelector(".indie3").classList.toggle("new")
    document.querySelector(".indie4").classList.toggle("new")
    document.querySelector(".indie5").classList.toggle("new")
    document.querySelector(".indie6").classList.toggle("new")
    document.querySelector(".indie7").classList.toggle("new")
    document.querySelector(".indie8").classList.toggle("new")
    document.querySelector(".indie9").classList.toggle("new")
    document.querySelector(".indie10").classList.toggle("new")
    document.querySelector(".indie11").classList.toggle("new")
    document.querySelector(".indie12").classList.toggle("new")
}
function hh(){
    document.querySelector('.album').classList.toggle("new2");
    document.querySelector(".kpop1").classList.toggle("new");
    document.querySelector(".kpop2").classList.toggle("new");
    document.querySelector(".kpop3").classList.toggle("new");
    document.querySelector(".kpop9").classList.toggle("new");
    document.querySelector(".kpop4").classList.toggle("new");
    document.querySelector(".kpop5").classList.toggle("new");
    document.querySelector(".kpop6").classList.toggle("new");
    document.querySelector(".kpop7").classList.toggle("new");
    document.querySelector(".kpop8").classList.toggle("new");
    document.querySelector(".rock1").classList.toggle("new")
    document.querySelector(".rock2").classList.toggle("new")
    document.querySelector(".rock3").classList.toggle("new")
    document.querySelector(".rock4").classList.toggle("new")
    document.querySelector(".rock5").classList.toggle("new")
    document.querySelector(".rock6").classList.toggle("new")
    document.querySelector(".rock7").classList.toggle("new")
    document.querySelector(".rock8").classList.toggle("new")
    document.querySelector(".rock9").classList.toggle("new")
    document.querySelector(".rock10").classList.toggle("new")
    document.querySelector(".rock11").classList.toggle("new")
    document.querySelector(".rock12").classList.toggle("new")
    document.querySelector(".rock13").classList.toggle("new")
    document.querySelector(".rock14").classList.toggle("new")
    document.querySelector(".rock15").classList.toggle("new")
    document.querySelector(".rb1").classList.toggle("new")
    document.querySelector(".rb2").classList.toggle("new")
    document.querySelector(".rb3").classList.toggle("new")
    document.querySelector(".rb4").classList.toggle("new")
    document.querySelector(".rb5").classList.toggle("new")
    document.querySelector(".rb6").classList.toggle("new")
    document.querySelector(".rb7").classList.toggle("new")
    document.querySelector(".rb8").classList.toggle("new")
    document.querySelector(".rb9").classList.toggle("new")
    document.querySelector(".rb10").classList.toggle("new")
    document.querySelector(".rb11").classList.toggle("new")
    document.querySelector(".indie1").classList.toggle("new")
    document.querySelector(".indie2").classList.toggle("new")
    document.querySelector(".indie3").classList.toggle("new")
    document.querySelector(".indie4").classList.toggle("new")
    document.querySelector(".indie5").classList.toggle("new")
    document.querySelector(".indie6").classList.toggle("new")
    document.querySelector(".indie7").classList.toggle("new")
    document.querySelector(".indie8").classList.toggle("new")
    document.querySelector(".indie9").classList.toggle("new")
    document.querySelector(".indie10").classList.toggle("new")
    document.querySelector(".indie11").classList.toggle("new")
    document.querySelector(".indie12").classList.toggle("new")
}
function kpop(){
    document.querySelector('.album').classList.toggle("new2");
    document.querySelector(".hiphop1").classList.toggle("new");
    document.querySelector(".hiphop2").classList.toggle("new")
    document.querySelector(".hiphop3").classList.toggle("new")
    document.querySelector(".hiphop4").classList.toggle("new")
    document.querySelector(".hiphop5").classList.toggle("new")
    document.querySelector(".hiphop6").classList.toggle("new")
    document.querySelector(".hiphop7").classList.toggle("new")
    document.querySelector(".hiphop8").classList.toggle("new")
    document.querySelector(".hiphop9").classList.toggle("new")
    document.querySelector(".hiphop10").classList.toggle("new")
    document.querySelector(".hiphop11").classList.toggle("new")
    document.querySelector(".hiphop12").classList.toggle("new")
    document.querySelector(".hiphop13").classList.toggle("new")
    document.querySelector(".hiphop14").classList.toggle("new")
    document.querySelector(".hiphop15").classList.toggle("new")
    document.querySelector(".hiphop16").classList.toggle("new")
    document.querySelector(".hiphop17").classList.toggle("new")
    document.querySelector(".hiphop18").classList.toggle("new")
    document.querySelector(".hiphop19").classList.toggle("new")
    document.querySelector(".hiphop20").classList.toggle("new")
    document.querySelector(".rock1").classList.toggle("new")
    document.querySelector(".rock2").classList.toggle("new")
    document.querySelector(".rock3").classList.toggle("new")
    document.querySelector(".rock4").classList.toggle("new")
    document.querySelector(".rock5").classList.toggle("new")
    document.querySelector(".rock6").classList.toggle("new")
    document.querySelector(".rock7").classList.toggle("new")
    document.querySelector(".rock8").classList.toggle("new")
    document.querySelector(".rock9").classList.toggle("new")
    document.querySelector(".rock10").classList.toggle("new")
    document.querySelector(".rock11").classList.toggle("new")
    document.querySelector(".rock12").classList.toggle("new")
    document.querySelector(".rock13").classList.toggle("new")
    document.querySelector(".rock14").classList.toggle("new")
    document.querySelector(".rock15").classList.toggle("new")
    document.querySelector(".rb1").classList.toggle("new")
    document.querySelector(".rb2").classList.toggle("new")
    document.querySelector(".rb3").classList.toggle("new")
    document.querySelector(".rb4").classList.toggle("new")
    document.querySelector(".rb5").classList.toggle("new")
    document.querySelector(".rb6").classList.toggle("new")
    document.querySelector(".rb7").classList.toggle("new")
    document.querySelector(".rb8").classList.toggle("new")
    document.querySelector(".rb9").classList.toggle("new")
    document.querySelector(".rb10").classList.toggle("new")
    document.querySelector(".rb11").classList.toggle("new")
    document.querySelector(".indie1").classList.toggle("new")
    document.querySelector(".indie2").classList.toggle("new")
    document.querySelector(".indie3").classList.toggle("new")
    document.querySelector(".indie4").classList.toggle("new")
    document.querySelector(".indie5").classList.toggle("new")
    document.querySelector(".indie6").classList.toggle("new")
    document.querySelector(".indie7").classList.toggle("new")
    document.querySelector(".indie8").classList.toggle("new")
    document.querySelector(".indie9").classList.toggle("new")
    document.querySelector(".indie10").classList.toggle("new")
    document.querySelector(".indie11").classList.toggle("new")
    document.querySelector(".indie12").classList.toggle("new")
}